# Generated by Django 6.0.6 on 2026-08-24 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('drop_address', models.TextField()),
                ('drop_latitude', models.FloatField()),
                ('drop_longitude', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('estimated_time', models.CharField(default='15 min', max_length=50)),
                ('cab_type', models.CharField(choices=[('Mini', 'Mini (₹10/km, 3 seats)'), ('Sedan', 'Sedan (₹15/km, 4 seats)'), ('SUV', 'SUV (₹20/km, 6 seats)')], default='Sedan', max_length=20)),
                ('base_fare', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI Payment'), ('Card', 'Debit/Credit Card')], default='Cash', max_length=20)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Driver Assigned', 'Driver Assigned'), ('On the Way', 'On the Way'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=30)),
                ('driver_name', models.CharField(default='Rahul Patel', max_length=100)),
                ('driver_vehicle', models.CharField(default='Swift Dzire', max_length=100)),
                ('driver_number', models.CharField(default='GJ03AB1234', max_length=20)),
                ('driver_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('driver_rating', models.FloatField(default=4.8)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
