# Generated by Django 6.0.6 on 2026-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this review from public pages'),
        ),
    ]
