# Generated by Django 6.0.6 on 2026-08-12 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='TasteTrail', max_length=100)),
                ('logo_icon', models.CharField(default='fa-utensils', max_length=50)),
                ('contact_email', models.EmailField(default='support@tastetrail.com', max_length=254)),
                ('contact_number', models.CharField(default='+91 98765 43210', max_length=20)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('default_location', models.CharField(default='Rajkot', max_length=100)),
                ('default_opening_time', models.TimeField(default='11:00')),
                ('default_closing_time', models.TimeField(default='23:00')),
                ('website_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_offer', 'New Offer'), ('order_update', 'Order Update'), ('reservation_conf', 'Reservation Confirmation'), ('restaurant_announcement', 'Restaurant Announcement'), ('general', 'General')], default='general', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, help_text='Leave blank for all users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
